In [2]:
import tensorflow as tf # 딥러닝 텐서플로 라이브러리
from sklearn import linear_model # 머신러닝 사이킷런 라이브러리
import numpy

In [4]:
# 전통적 방식의 프로그램
def process(x):
  y = 5 * x + 7
  return y

result = process(10)
print(result)

57


In [5]:
# Machine learning
X_train = numpy.array([1,2,3,4,5,6,7]).reshape(-1,1) # 문제 cf. reshape(-1,1) = 열은 1로 고정, 행은 자동 계산하라는 뜻
y_train = numpy.array([12,17,22,27,32,37,42]).reshape(-1,1) # 정답

# 선형회귀 알고리즘 구현 클래스 - 깡통
model = linear_model.LinearRegression()
model.fit(X_train, y_train) # 학습

# 문제 내기 - 예측
model.predict([[9]]) # y = wx + b

array([[52.]])

In [6]:
model.coef_, model.intercept_ # w, b

(array([[5.]]), array([7.]))

In [ ]:
from scipy.linalg import null_space

In [15]:
# Deep learning
X_train = numpy.array([1,2,3,4,5,6,7]).reshape(-1,1) # 문제 cf. reshape(-1,1) = 열은 1로 고정, 행은 자동 계산하라는 뜻
y_train = numpy.array([12,17,22,27,32,37,42]).reshape(-1,1) # 정답

inputs = tf.keras.layers.Input(shape=(1,)) # 입력층 정의
outputs = tf.keras.layers.Dense(units=1)(inputs) #출력층

# 깡통 준비
model = tf.keras.models.Model(inputs,outputs)
model.compile(loss=tf.keras.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.SGD())

model.fit(X_train, y_train, epochs=500, verbose=0) # 학습
model.predict(numpy.array([[9]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[52.704884]], dtype=float32)